//! Golden values for the ported `ggml-quants.c`.
//!
//! # Provenance
//!
//! **Not a port, and not hand-written.** Generated by
//! `harness/quants_golden.c` run against the C reference build at
//! v0.3.0 (`c1d0e7a00`). Regenerate with `scripts/quants-golden`.
//!
//! # Why these exist
//!
//! A quantizer is easy to test wrongly: quantize, dequantize, check the
//! error is small, and the test passes with both halves broken in the
//! same way. These checksums come from the C, so the port is measured
//! against what it is replacing rather than against itself.
//!
//! `ref` is FNV-1a over the bytes `quantize_row_*_ref` writes for a
//! fixed input; `deq` over the floats `dequantize_row_*` gives back;
//! `chunk` and `chunk_imatrix` over `quantize_*` without and with an
//! importance matrix. A null field means the C has no such entry point
//! for that type, which is itself part of the contract.
//!
//! # The five input patterns
//!
//! Each type is captured against every one of them. Random input alone
//! leaves `amax` never zero, so the divide-by-zero guard at the top of
//! every symmetric quantizer would go untested -- and an all-zero block
//! is what a pruned row or a padded tail produces.
//!
//! - `random`      the common path
//! - `zeros`       amax == 0, taking that guard
//! - `constant`    min == max, the asymmetric formats degenerate range
//! - `outlier`     one huge value among tiny ones: extreme scale ratio
//! - `alternating` +v, -v, ...: sign handling, and max != amax

/// One type's golden values.
pub const Golden = struct {
    name: []const u8,
    pattern: []const u8,
    type: c_int,
    row_size: usize,
    ref: ?u64 = null,
    deq: ?u64 = null,
    chunk: ?u64 = null,
    chunk_imatrix: ?u64 = null,
    chunk_bytes: usize = 0,
};

/// Input shape the values were captured with. The test must use the
/// same, and the same generator, or nothing matches.
pub const n_per_row: usize = 256;
pub const n_rows: usize = 4;

pub const all = [_]Golden{
    .{ .name = "Q4_0", .pattern = "random", .type = 2, .row_size = 144, .ref = 0x2400a3e8defd8a5f, .deq = 0x7c522291ef67305f, .chunk = 0x2400a3e8defd8a5f, .chunk_bytes = 576, .chunk_imatrix = 0xe70bc7fc27f401cd },
    .{ .name = "Q4_0", .pattern = "zeros", .type = 2, .row_size = 144, .ref = 0xfac7bf22d68b3025, .deq = 0xcec286564e3b6325, .chunk = 0xfac7bf22d68b3025, .chunk_bytes = 576, .chunk_imatrix = 0xb9d0059d61083025 },
    .{ .name = "Q4_0", .pattern = "constant", .type = 2, .row_size = 144, .ref = 0x052d2ce926624b25, .deq = 0xcabae34748b6c325, .chunk = 0x052d2ce926624b25, .chunk_bytes = 576, .chunk_imatrix = 0x2d01c0bbf17d4425 },
    .{ .name = "Q4_0", .pattern = "outlier", .type = 2, .row_size = 144, .ref = 0x7a1e751f0c1c37ad, .deq = 0x3186590d14bbe905, .chunk = 0x7a1e751f0c1c37ad, .chunk_bytes = 576, .chunk_imatrix = 0x3a69b2aa32460dad },
    .{ .name = "Q4_0", .pattern = "alternating", .type = 2, .row_size = 144, .ref = 0xaea206854483aca5, .deq = 0x1311ee63ad360325, .chunk = 0xaea206854483aca5, .chunk_bytes = 576, .chunk_imatrix = 0x2b4a9b43c5c9df25 },
    .{ .name = "Q4_1", .pattern = "random", .type = 3, .row_size = 160, .ref = 0x6195d582a9150ea1, .deq = 0x44a42280f156b5e0, .chunk = 0x6195d582a9150ea1, .chunk_bytes = 640, .chunk_imatrix = 0xe40c70daa247f09d },
    .{ .name = "Q4_1", .pattern = "zeros", .type = 3, .row_size = 160, .ref = 0x96554ce2cfb01525, .deq = 0xb93a0c83ce3b6325, .chunk = 0x96554ce2cfb01525, .chunk_bytes = 640, .chunk_imatrix = 0x96554ce2cfb01525 },
    .{ .name = "Q4_1", .pattern = "constant", .type = 3, .row_size = 160, .ref = 0x47d0d620361aeb25, .deq = 0xcabae34748b6c325, .chunk = 0x47d0d620361aeb25, .chunk_bytes = 640, .chunk_imatrix = 0xf484ceffe87d7625 },
    .{ .name = "Q4_1", .pattern = "outlier", .type = 3, .row_size = 160, .ref = 0x55d764d689657f75, .deq = 0x0e335784df942bc5, .chunk = 0x55d764d689657f75, .chunk_bytes = 640, .chunk_imatrix = 0x5c3da78f1176bd7d },
    .{ .name = "Q4_1", .pattern = "alternating", .type = 3, .row_size = 160, .ref = 0xa61a00ccbc5c8625, .deq = 0xf347078467dd8b25, .chunk = 0xa61a00ccbc5c8625, .chunk_bytes = 640, .chunk_imatrix = 0xa61a00ccbc5c8625 },
    .{ .name = "Q5_0", .pattern = "random", .type = 6, .row_size = 176, .ref = 0x55245e0d51750b02, .deq = 0x2f6dce9b85626d01, .chunk = 0x55245e0d51750b02, .chunk_bytes = 704, .chunk_imatrix = 0x2a76dc9fdce2ed52 },
    .{ .name = "Q5_0", .pattern = "zeros", .type = 6, .row_size = 176, .ref = 0x5a951291e801fda5, .deq = 0xcec286564e3b6325, .chunk = 0x5a951291e801fda5, .chunk_bytes = 704, .chunk_imatrix = 0xcf58746c2dfcfa25 },
    .{ .name = "Q5_0", .pattern = "constant", .type = 6, .row_size = 176, .ref = 0xf399282af2bb1b25, .deq = 0xcabae34748b6c325, .chunk = 0xf399282af2bb1b25, .chunk_bytes = 704, .chunk_imatrix = 0x3cafc1c3341f10e5 },
    .{ .name = "Q5_0", .pattern = "outlier", .type = 6, .row_size = 176, .ref = 0xab7753a4ff1a189d, .deq = 0x3186590d14bbe905, .chunk = 0xab7753a4ff1a189d, .chunk_bytes = 704, .chunk_imatrix = 0xf6216760a602cb25 },
    .{ .name = "Q5_0", .pattern = "alternating", .type = 6, .row_size = 176, .ref = 0xa16b0a3f5e3abf25, .deq = 0xbb3c9dbe2b37a325, .chunk = 0xa16b0a3f5e3abf25, .chunk_bytes = 704, .chunk_imatrix = 0x041255b220acf965 },
    .{ .name = "Q5_1", .pattern = "random", .type = 7, .row_size = 192, .ref = 0x63a1501be9fda39c, .deq = 0x3724118c7c8646a4, .chunk = 0x63a1501be9fda39c, .chunk_bytes = 768, .chunk_imatrix = 0x27240bead0526c32 },
    .{ .name = "Q5_1", .pattern = "zeros", .type = 7, .row_size = 192, .ref = 0x9fa9e040e0eedf25, .deq = 0xb93a0c83ce3b6325, .chunk = 0x9fa9e040e0eedf25, .chunk_bytes = 768, .chunk_imatrix = 0x9fa9e040e0eedf25 },
    .{ .name = "Q5_1", .pattern = "constant", .type = 7, .row_size = 192, .ref = 0x09ba218601210325, .deq = 0xcabae34748b6c325, .chunk = 0x09ba218601210325, .chunk_bytes = 768, .chunk_imatrix = 0xe130c8e51bfd1125 },
    .{ .name = "Q5_1", .pattern = "outlier", .type = 7, .row_size = 192, .ref = 0xaae64198b2b1d0d5, .deq = 0x1cf44a3453df5705, .chunk = 0xaae64198b2b1d0d5, .chunk_bytes = 768, .chunk_imatrix = 0xcedf4a50e56f4185 },
    .{ .name = "Q5_1", .pattern = "alternating", .type = 7, .row_size = 192, .ref = 0x2c9cfc9b6fae66a5, .deq = 0xe625aed4812ddf25, .chunk = 0x2c9cfc9b6fae66a5, .chunk_bytes = 768, .chunk_imatrix = 0x4e48cef445b788a5 },
    .{ .name = "Q8_0", .pattern = "random", .type = 8, .row_size = 272, .ref = 0xbf7ff5230ccc3b90, .deq = 0x337eba23f71d42d1, .chunk = 0xbf7ff5230ccc3b90, .chunk_bytes = 1088, .chunk_imatrix = 0xbf7ff5230ccc3b90 },
    .{ .name = "Q8_0", .pattern = "zeros", .type = 8, .row_size = 272, .ref = 0xc4a024f324535825, .deq = 0xb93a0c83ce3b6325, .chunk = 0xc4a024f324535825, .chunk_bytes = 1088, .chunk_imatrix = 0xc4a024f324535825 },
    .{ .name = "Q8_0", .pattern = "constant", .type = 8, .row_size = 272, .ref = 0x25404c6852b6a125, .deq = 0x096c72cd4c478b25, .chunk = 0x25404c6852b6a125, .chunk_bytes = 1088, .chunk_imatrix = 0x25404c6852b6a125 },
    .{ .name = "Q8_0", .pattern = "outlier", .type = 8, .row_size = 272, .ref = 0x1ac9913be533d68d, .deq = 0xf416c6f36be3d1a5, .chunk = 0x1ac9913be533d68d, .chunk_bytes = 1088, .chunk_imatrix = 0x1ac9913be533d68d },
    .{ .name = "Q8_0", .pattern = "alternating", .type = 8, .row_size = 272, .ref = 0xad1980b78dda01e5, .deq = 0x8fb485f9f750fb25, .chunk = 0xad1980b78dda01e5, .chunk_bytes = 1088, .chunk_imatrix = 0xad1980b78dda01e5 },
    .{ .name = "Q8_1", .pattern = "random", .type = 9, .row_size = 288, .ref = 0xff6069ef71ae5c0e },
    .{ .name = "Q8_1", .pattern = "zeros", .type = 9, .row_size = 288, .ref = 0x36fe4d3f1c233d25 },
    .{ .name = "Q8_1", .pattern = "constant", .type = 9, .row_size = 288, .ref = 0xce942b5f83496d25 },
    .{ .name = "Q8_1", .pattern = "outlier", .type = 9, .row_size = 288, .ref = 0xdc026c7c2547a105 },
    .{ .name = "Q8_1", .pattern = "alternating", .type = 9, .row_size = 288, .ref = 0xd527bbe05359e465 },
    .{ .name = "Q1_0", .pattern = "random", .type = 41, .row_size = 36, .ref = 0x5923c3dc129e412e, .deq = 0xf63d0c22330be3a5, .chunk = 0x5923c3dc129e412e, .chunk_bytes = 144, .chunk_imatrix = 0x5923c3dc129e412e },
    .{ .name = "Q1_0", .pattern = "zeros", .type = 41, .row_size = 36, .ref = 0xe76ad1c291f595e5, .deq = 0xb93a0c83ce3b6325, .chunk = 0xe76ad1c291f595e5, .chunk_bytes = 144, .chunk_imatrix = 0xe76ad1c291f595e5 },
    .{ .name = "Q1_0", .pattern = "constant", .type = 41, .row_size = 36, .ref = 0x44ea8cabd1c75325, .deq = 0xcabae34748b6c325, .chunk = 0x44ea8cabd1c75325, .chunk_bytes = 144, .chunk_imatrix = 0x44ea8cabd1c75325 },
    .{ .name = "Q1_0", .pattern = "outlier", .type = 41, .row_size = 36, .ref = 0x9021dc674f0bfdad, .deq = 0x5e635efbbff51725, .chunk = 0x9021dc674f0bfdad, .chunk_bytes = 144, .chunk_imatrix = 0x9021dc674f0bfdad },
    .{ .name = "Q1_0", .pattern = "alternating", .type = 41, .row_size = 36, .ref = 0x29fb80723b04d485, .deq = 0x97f83fad95d6c325, .chunk = 0x29fb80723b04d485, .chunk_bytes = 144, .chunk_imatrix = 0x29fb80723b04d485 },
    .{ .name = "Q2_0", .pattern = "random", .type = 42, .row_size = 72, .ref = 0x8754dc404b04ec95, .deq = 0x800fbca594cf20a4, .chunk = 0x8754dc404b04ec95, .chunk_bytes = 288, .chunk_imatrix = 0x8754dc404b04ec95 },
    .{ .name = "Q2_0", .pattern = "zeros", .type = 42, .row_size = 72, .ref = 0xb11877b831e406a5, .deq = 0xb93a0c83ce3b6325, .chunk = 0xb11877b831e406a5, .chunk_bytes = 288, .chunk_imatrix = 0xb11877b831e406a5 },
    .{ .name = "Q2_0", .pattern = "constant", .type = 42, .row_size = 72, .ref = 0xfe603341ff864325, .deq = 0xcabae34748b6c325, .chunk = 0xfe603341ff864325, .chunk_bytes = 288, .chunk_imatrix = 0xfe603341ff864325 },
    .{ .name = "Q2_0", .pattern = "outlier", .type = 42, .row_size = 72, .ref = 0x9c8e8676d38bf45d, .deq = 0x7b5e21236785d405, .chunk = 0x9c8e8676d38bf45d, .chunk_bytes = 288, .chunk_imatrix = 0x9c8e8676d38bf45d },
    .{ .name = "Q2_0", .pattern = "alternating", .type = 42, .row_size = 72, .ref = 0x9227f4f0c35651e5, .deq = 0x97f83fad95d6c325, .chunk = 0x9227f4f0c35651e5, .chunk_bytes = 288, .chunk_imatrix = 0x9227f4f0c35651e5 },
    .{ .name = "MXFP4", .pattern = "random", .type = 39, .row_size = 136, .ref = 0xdc281dbe413ec133, .deq = 0xd9148bbf4d210b4b, .chunk = 0xdc281dbe413ec133, .chunk_bytes = 544, .chunk_imatrix = 0xdc281dbe413ec133 },
    .{ .name = "MXFP4", .pattern = "zeros", .type = 39, .row_size = 136, .ref = 0x9986ba9af2021da5, .deq = 0xb93a0c83ce3b6325, .chunk = 0x9986ba9af2021da5, .chunk_bytes = 544, .chunk_imatrix = 0x9986ba9af2021da5 },
    .{ .name = "MXFP4", .pattern = "constant", .type = 39, .row_size = 136, .ref = 0x4cc2114aa6c41b25, .deq = 0xcabae34748b6c325, .chunk = 0x4cc2114aa6c41b25, .chunk_bytes = 544, .chunk_imatrix = 0x4cc2114aa6c41b25 },
    .{ .name = "MXFP4", .pattern = "outlier", .type = 39, .row_size = 136, .ref = 0xad39a5eaba7d54a5, .deq = 0x159102296e15b725, .chunk = 0xad39a5eaba7d54a5, .chunk_bytes = 544, .chunk_imatrix = 0xad39a5eaba7d54a5 },
    .{ .name = "MXFP4", .pattern = "alternating", .type = 39, .row_size = 136, .ref = 0x50da875adfdef585, .deq = 0x64a325a7b0b6c325, .chunk = 0x50da875adfdef585, .chunk_bytes = 544, .chunk_imatrix = 0x50da875adfdef585 },
    .{ .name = "NVFP4", .pattern = "random", .type = 40, .row_size = 144, .ref = 0x8e3e58d3d704fde5, .deq = 0x09faac91eda05642, .chunk = 0x8e3e58d3d704fde5, .chunk_bytes = 576, .chunk_imatrix = 0x8e3e58d3d704fde5 },
    .{ .name = "NVFP4", .pattern = "zeros", .type = 40, .row_size = 144, .ref = 0xb9d0059d61083025, .deq = 0xb93a0c83ce3b6325, .chunk = 0xb9d0059d61083025, .chunk_bytes = 576, .chunk_imatrix = 0xb9d0059d61083025 },
    .{ .name = "NVFP4", .pattern = "constant", .type = 40, .row_size = 144, .ref = 0x2d1f5a3a55d5a165, .deq = 0x5fadd5aeecfd8325, .chunk = 0x2d1f5a3a55d5a165, .chunk_bytes = 576, .chunk_imatrix = 0x2d1f5a3a55d5a165 },
    .{ .name = "NVFP4", .pattern = "outlier", .type = 40, .row_size = 144, .ref = 0xaf88ad990057fe65, .deq = 0x954e6bbc43657f25, .chunk = 0xaf88ad990057fe65, .chunk_bytes = 576, .chunk_imatrix = 0xaf88ad990057fe65 },
    .{ .name = "NVFP4", .pattern = "alternating", .type = 40, .row_size = 144, .ref = 0x8c14033a64b01c65, .deq = 0xd5744ba85f8ee325, .chunk = 0x8c14033a64b01c65, .chunk_bytes = 576, .chunk_imatrix = 0x8c14033a64b01c65 },
    .{ .name = "Q2_K", .pattern = "random", .type = 10, .row_size = 84, .ref = 0xa4f7eb6f6e301afc, .deq = 0xa635ea4cadea0212, .chunk = 0xa4f7eb6f6e301afc, .chunk_bytes = 336, .chunk_imatrix = 0x092bd190c6dd04bd },
    .{ .name = "Q2_K", .pattern = "zeros", .type = 10, .row_size = 84, .ref = 0x51795983e22e1d65, .deq = 0xb93a0c83ce3b6325, .chunk = 0x51795983e22e1d65, .chunk_bytes = 336, .chunk_imatrix = 0x51795983e22e1d65 },
    .{ .name = "Q2_K", .pattern = "constant", .type = 10, .row_size = 84, .ref = 0x6e351ec10d3d9185, .deq = 0x0131e4207f948b25, .chunk = 0x6e351ec10d3d9185, .chunk_bytes = 336, .chunk_imatrix = 0x6e351ec10d3d9185 },
    .{ .name = "Q2_K", .pattern = "outlier", .type = 10, .row_size = 84, .ref = 0x8061bc2f2893cb25, .deq = 0x2d45d78fd8b0f065, .chunk = 0x8061bc2f2893cb25, .chunk_bytes = 336, .chunk_imatrix = 0x8061bc2f2893cb25 },
    .{ .name = "Q2_K", .pattern = "alternating", .type = 10, .row_size = 84, .ref = 0x9f6ca4d412e55fed, .deq = 0xc43929b670dca325, .chunk = 0x9f6ca4d412e55fed, .chunk_bytes = 336, .chunk_imatrix = 0x9f6ca4d412e55fed },
    .{ .name = "Q3_K", .pattern = "random", .type = 11, .row_size = 110, .ref = 0xe2a65cfbed0417e7, .deq = 0x763059f225dba044, .chunk = 0xe2a65cfbed0417e7, .chunk_bytes = 440, .chunk_imatrix = 0xff227eb3ec71f6d1 },
    .{ .name = "Q3_K", .pattern = "zeros", .type = 11, .row_size = 110, .ref = 0x08fd0a89c6878385, .deq = 0xb93a0c83ce3b6325, .chunk = 0x08fd0a89c6878385, .chunk_bytes = 440, .chunk_imatrix = 0x08fd0a89c6878385 },
    .{ .name = "Q3_K", .pattern = "constant", .type = 11, .row_size = 110, .ref = 0x213c92a175ddd665, .deq = 0xcabae34748b6c325, .chunk = 0x213c92a175ddd665, .chunk_bytes = 440, .chunk_imatrix = 0x85bb4597bbc4377d },
    .{ .name = "Q3_K", .pattern = "outlier", .type = 11, .row_size = 110, .ref = 0xe6b08f46b769e81d, .deq = 0xe6efd06269318405, .chunk = 0xe6b08f46b769e81d, .chunk_bytes = 440, .chunk_imatrix = 0xe9283849dc67fc1d },
    .{ .name = "Q3_K", .pattern = "alternating", .type = 11, .row_size = 110, .ref = 0x508532038375da3d, .deq = 0x82396448dfffd325, .chunk = 0x508532038375da3d, .chunk_bytes = 440, .chunk_imatrix = 0x73b16d5d0a1f53ed },
    .{ .name = "Q4_K", .pattern = "random", .type = 12, .row_size = 144, .ref = 0x12a2d060cf525266, .deq = 0x18c64caa1e58cd11, .chunk = 0x12a2d060cf525266, .chunk_bytes = 576, .chunk_imatrix = 0x9eb84bd7e323ee79 },
    .{ .name = "Q4_K", .pattern = "zeros", .type = 12, .row_size = 144, .ref = 0xb9d0059d61083025, .deq = 0xb93a0c83ce3b6325, .chunk = 0xb9d0059d61083025, .chunk_bytes = 576, .chunk_imatrix = 0xb9d0059d61083025 },
    .{ .name = "Q4_K", .pattern = "constant", .type = 12, .row_size = 144, .ref = 0xe9e9d1b34a502285, .deq = 0xf62f9ec5f29f4325, .chunk = 0xe9e9d1b34a502285, .chunk_bytes = 576, .chunk_imatrix = 0xe9e9d1b34a502285 },
    .{ .name = "Q4_K", .pattern = "outlier", .type = 12, .row_size = 144, .ref = 0xb7382cdda5e680ed, .deq = 0xf5763959b938fd45, .chunk = 0xb7382cdda5e680ed, .chunk_bytes = 576, .chunk_imatrix = 0xb7382cdda5e680ed },
    .{ .name = "Q4_K", .pattern = "alternating", .type = 12, .row_size = 144, .ref = 0x24724b1515dae885, .deq = 0xc8a0dbb42c17c725, .chunk = 0x24724b1515dae885, .chunk_bytes = 576, .chunk_imatrix = 0x24724b1515dae885 },
    .{ .name = "Q5_K", .pattern = "random", .type = 13, .row_size = 176, .ref = 0x3852d6843074ae3f, .deq = 0xf80516722e66a8e2, .chunk = 0x3852d6843074ae3f, .chunk_bytes = 704, .chunk_imatrix = 0x4732c09e58cdf953 },
    .{ .name = "Q5_K", .pattern = "zeros", .type = 13, .row_size = 176, .ref = 0xcf58746c2dfcfa25, .deq = 0xb93a0c83ce3b6325, .chunk = 0xcf58746c2dfcfa25, .chunk_bytes = 704, .chunk_imatrix = 0xcf58746c2dfcfa25 },
    .{ .name = "Q5_K", .pattern = "constant", .type = 13, .row_size = 176, .ref = 0x583a0519ae3ba805, .deq = 0x7315f325f3866325, .chunk = 0x583a0519ae3ba805, .chunk_bytes = 704, .chunk_imatrix = 0x583a0519ae3ba805 },
    .{ .name = "Q5_K", .pattern = "outlier", .type = 13, .row_size = 176, .ref = 0x6fb5da8f38fa2195, .deq = 0xc41e5fb189f1cba5, .chunk = 0x6fb5da8f38fa2195, .chunk_bytes = 704, .chunk_imatrix = 0x6fb5da8f38fa2195 },
    .{ .name = "Q5_K", .pattern = "alternating", .type = 13, .row_size = 176, .ref = 0x4f2a5b23ed5e54e5, .deq = 0xc8a0dbb42c17c725, .chunk = 0x4f2a5b23ed5e54e5, .chunk_bytes = 704, .chunk_imatrix = 0x646989250dedb715 },
    .{ .name = "Q6_K", .pattern = "random", .type = 14, .row_size = 210, .ref = 0x1c333cfbdd2bc1df, .deq = 0xf88d536b7bd40738, .chunk = 0x1c333cfbdd2bc1df, .chunk_bytes = 840, .chunk_imatrix = 0x1b3884e39b4baad0 },
    .{ .name = "Q6_K", .pattern = "zeros", .type = 14, .row_size = 210, .ref = 0xdb696f78397bfac5, .deq = 0xcec286564e3b6325, .chunk = 0xdb696f78397bfac5, .chunk_bytes = 840, .chunk_imatrix = 0xdb696f78397bfac5 },
    .{ .name = "Q6_K", .pattern = "constant", .type = 14, .row_size = 210, .ref = 0x358964aa44d588e5, .deq = 0xcabae34748b6c325, .chunk = 0x358964aa44d588e5, .chunk_bytes = 840, .chunk_imatrix = 0x48470bea190f2cd5 },
    .{ .name = "Q6_K", .pattern = "outlier", .type = 14, .row_size = 210, .ref = 0x694b29e79c899d05, .deq = 0xe6efd06269318405, .chunk = 0x694b29e79c899d05, .chunk_bytes = 840, .chunk_imatrix = 0xf272568fa851ea05 },
    .{ .name = "Q6_K", .pattern = "alternating", .type = 14, .row_size = 210, .ref = 0x484192ed54636a7d, .deq = 0x45c02cd25f07c325, .chunk = 0x484192ed54636a7d, .chunk_bytes = 840, .chunk_imatrix = 0x484192ed54636a7d },
    .{ .name = "Q8_K", .pattern = "random", .type = 15, .row_size = 292, .ref = 0xf3bff5c58a290432, .deq = 0x18560d1ffca20a1a },
    .{ .name = "Q8_K", .pattern = "zeros", .type = 15, .row_size = 292, .ref = 0xa35541ff35b6fe65, .deq = 0xb93a0c83ce3b6325 },
    .{ .name = "Q8_K", .pattern = "constant", .type = 15, .row_size = 292, .ref = 0x69f9545e388f760d, .deq = 0xcabae34748b6c325 },
    .{ .name = "Q8_K", .pattern = "outlier", .type = 15, .row_size = 292, .ref = 0x96cb818be9dbf525, .deq = 0xe6efd06269318405 },
    .{ .name = "Q8_K", .pattern = "alternating", .type = 15, .row_size = 292, .ref = 0x57640ef5a1505e05, .deq = 0x97f83fad95d6c325 },
    .{ .name = "TQ1_0", .pattern = "random", .type = 34, .row_size = 54, .ref = 0x6005aae25e569ea5, .deq = 0x701159c6ce09b541, .chunk = 0x6005aae25e569ea5, .chunk_bytes = 216, .chunk_imatrix = 0x6005aae25e569ea5 },
    .{ .name = "TQ1_0", .pattern = "zeros", .type = 34, .row_size = 54, .ref = 0x278bb20f1da14ab5, .deq = 0xb93a0c83ce3b6325, .chunk = 0x278bb20f1da14ab5, .chunk_bytes = 216, .chunk_imatrix = 0x278bb20f1da14ab5 },
    .{ .name = "TQ1_0", .pattern = "constant", .type = 34, .row_size = 54, .ref = 0x2403fcd9dc2b9115, .deq = 0xcabae34748b6c325, .chunk = 0x2403fcd9dc2b9115, .chunk_bytes = 216, .chunk_imatrix = 0x2403fcd9dc2b9115 },
    .{ .name = "TQ1_0", .pattern = "outlier", .type = 34, .row_size = 54, .ref = 0x4bbfb746f7c3ef45, .deq = 0x191258dc0e1d2005, .chunk = 0x4bbfb746f7c3ef45, .chunk_bytes = 216, .chunk_imatrix = 0x4bbfb746f7c3ef45 },
    .{ .name = "TQ1_0", .pattern = "alternating", .type = 34, .row_size = 54, .ref = 0x40352d670f299cf5, .deq = 0x97f83fad95d6c325, .chunk = 0x40352d670f299cf5, .chunk_bytes = 216, .chunk_imatrix = 0x40352d670f299cf5 },
    .{ .name = "TQ2_0", .pattern = "random", .type = 35, .row_size = 66, .ref = 0x526b5cdb0cff6e13, .deq = 0x701159c6ce09b541, .chunk = 0x526b5cdb0cff6e13, .chunk_bytes = 264, .chunk_imatrix = 0x526b5cdb0cff6e13 },
    .{ .name = "TQ2_0", .pattern = "zeros", .type = 35, .row_size = 66, .ref = 0x3af5b5ea445dd4c5, .deq = 0xb93a0c83ce3b6325, .chunk = 0x3af5b5ea445dd4c5, .chunk_bytes = 264, .chunk_imatrix = 0x3af5b5ea445dd4c5 },
    .{ .name = "TQ2_0", .pattern = "constant", .type = 35, .row_size = 66, .ref = 0x80d4f64d24dbf925, .deq = 0xcabae34748b6c325, .chunk = 0x80d4f64d24dbf925, .chunk_bytes = 264, .chunk_imatrix = 0x80d4f64d24dbf925 },
    .{ .name = "TQ2_0", .pattern = "outlier", .type = 35, .row_size = 66, .ref = 0x3942105bb18916b5, .deq = 0x191258dc0e1d2005, .chunk = 0x3942105bb18916b5, .chunk_bytes = 264, .chunk_imatrix = 0x3942105bb18916b5 },
    .{ .name = "TQ2_0", .pattern = "alternating", .type = 35, .row_size = 66, .ref = 0x6906595266349dd5, .deq = 0x97f83fad95d6c325, .chunk = 0x6906595266349dd5, .chunk_bytes = 264, .chunk_imatrix = 0x6906595266349dd5 },
    .{ .name = "IQ2_XXS", .pattern = "random", .type = 16, .row_size = 66, .deq = 0xc9c84210a073f909, .chunk_imatrix = 0x9afacc1c1fae49cb, .chunk_bytes = 264 },
    .{ .name = "IQ2_XXS", .pattern = "zeros", .type = 16, .row_size = 66, .deq = 0xb93a0c83ce3b6325, .chunk_imatrix = 0x92184cc8715e4dc5, .chunk_bytes = 264 },
    .{ .name = "IQ2_XXS", .pattern = "constant", .type = 16, .row_size = 66, .deq = 0x7862f2679e7d6ea5, .chunk_imatrix = 0x9a244edf04ed28bd, .chunk_bytes = 264 },
    .{ .name = "IQ2_XXS", .pattern = "outlier", .type = 16, .row_size = 66, .deq = 0xa17e9cc4a8205b65, .chunk_imatrix = 0xb97ab000d963e755, .chunk_bytes = 264 },
    .{ .name = "IQ2_XXS", .pattern = "alternating", .type = 16, .row_size = 66, .deq = 0xf945b936beab8b85, .chunk_imatrix = 0x41ac5ed247d57efd, .chunk_bytes = 264 },
    .{ .name = "IQ2_XS", .pattern = "random", .type = 17, .row_size = 74, .deq = 0xe9a7b958bff9e885, .chunk_imatrix = 0x97163d36e85b6fd2, .chunk_bytes = 296 },
    .{ .name = "IQ2_XS", .pattern = "zeros", .type = 17, .row_size = 74, .deq = 0xb93a0c83ce3b6325, .chunk_imatrix = 0x5350442c19447045, .chunk_bytes = 296 },
    .{ .name = "IQ2_XS", .pattern = "constant", .type = 17, .row_size = 74, .deq = 0x48a789c9ab5d4325, .chunk_imatrix = 0x04e55b990c7cbf2d, .chunk_bytes = 296 },
    .{ .name = "IQ2_XS", .pattern = "outlier", .type = 17, .row_size = 74, .deq = 0x2c0a8bf9997a262d, .chunk_imatrix = 0x717bf5b23e7301a5, .chunk_bytes = 296 },
    .{ .name = "IQ2_XS", .pattern = "alternating", .type = 17, .row_size = 74, .deq = 0x863b9fa0945e0325, .chunk_imatrix = 0x34d35287d79573d5, .chunk_bytes = 296 },
    .{ .name = "IQ1_S", .pattern = "random", .type = 19, .row_size = 50, .deq = 0xdf0d8fee19d1d5dc, .chunk_imatrix = 0xa3a0d33cbdb63eeb, .chunk_bytes = 200 },
    .{ .name = "IQ1_S", .pattern = "zeros", .type = 19, .row_size = 50, .deq = 0xcec286564e3b6325, .chunk_imatrix = 0x37027190f725c8c5, .chunk_bytes = 200 },
    .{ .name = "IQ1_S", .pattern = "constant", .type = 19, .row_size = 50, .deq = 0x40afb8537a95d425, .chunk_imatrix = 0x016d99ee450af6c5, .chunk_bytes = 200 },
    .{ .name = "IQ1_S", .pattern = "outlier", .type = 19, .row_size = 50, .deq = 0x8bf918952b00e4e5, .chunk_imatrix = 0x18ed0e750b5f8485, .chunk_bytes = 200 },
    .{ .name = "IQ1_S", .pattern = "alternating", .type = 19, .row_size = 50, .deq = 0x685a1eb97b34c825, .chunk_imatrix = 0x208ae8ac11f3783d, .chunk_bytes = 200 },
    .{ .name = "IQ1_M", .pattern = "random", .type = 29, .row_size = 56, .deq = 0x3239c11aebae7304, .chunk = 0x43a7028842547124, .chunk_bytes = 224, .chunk_imatrix = 0xa8e6bf815fe1030c },
    .{ .name = "IQ1_M", .pattern = "zeros", .type = 29, .row_size = 56, .deq = 0xcec286564e3b6325, .chunk = 0xcc6a1ff5f8a224a5, .chunk_bytes = 224, .chunk_imatrix = 0xcc6a1ff5f8a224a5 },
    .{ .name = "IQ1_M", .pattern = "constant", .type = 29, .row_size = 56, .deq = 0x4844d9d18e546c25, .chunk = 0xf46fb6a488dd10c5, .chunk_bytes = 224, .chunk_imatrix = 0x8a0f43c641d26f6d },
    .{ .name = "IQ1_M", .pattern = "outlier", .type = 29, .row_size = 56, .deq = 0xd2288c315260c005, .chunk = 0x3801bed14baeb925, .chunk_bytes = 224, .chunk_imatrix = 0xd96956a19f4c18b5 },
    .{ .name = "IQ1_M", .pattern = "alternating", .type = 29, .row_size = 56, .deq = 0xd72186c801478ba5, .chunk = 0xacbaa3d17be91345, .chunk_bytes = 224, .chunk_imatrix = 0x73bbbb10e040a725 },
    .{ .name = "IQ2_S", .pattern = "random", .type = 22, .row_size = 82, .ref = 0xe8313d0219f57bda, .deq = 0x683b62129457961d, .chunk = 0xe8313d0219f57bda, .chunk_bytes = 328, .chunk_imatrix = 0x43e1ec792bc21011 },
    .{ .name = "IQ2_S", .pattern = "zeros", .type = 22, .row_size = 82, .ref = 0xb11fcf5763dbd2c5, .deq = 0xb93a0c83ce3b6325, .chunk = 0xb11fcf5763dbd2c5, .chunk_bytes = 328, .chunk_imatrix = 0xb11fcf5763dbd2c5 },
    .{ .name = "IQ2_S", .pattern = "constant", .type = 22, .row_size = 82, .ref = 0x16b1a327aef3d045, .deq = 0xd216882c15f22325, .chunk = 0x16b1a327aef3d045, .chunk_bytes = 328, .chunk_imatrix = 0x16b1a327aef3d045 },
    .{ .name = "IQ2_S", .pattern = "outlier", .type = 22, .row_size = 82, .ref = 0x9ef14647e70123d5, .deq = 0x80745ce75a1b0c15, .chunk = 0x9ef14647e70123d5, .chunk_bytes = 328, .chunk_imatrix = 0xa296d52e9236740d },
    .{ .name = "IQ2_S", .pattern = "alternating", .type = 22, .row_size = 82, .ref = 0xb74185f110832885, .deq = 0xdac43427d23c9b25, .chunk = 0xb74185f110832885, .chunk_bytes = 328, .chunk_imatrix = 0xb74185f110832885 },
    .{ .name = "IQ3_XXS", .pattern = "random", .type = 18, .row_size = 98, .ref = 0x6426248da88b786b, .deq = 0x0b944bb36274fd2d, .chunk = 0x6426248da88b786b, .chunk_bytes = 392, .chunk_imatrix = 0xd5129603a3c38bff },
    .{ .name = "IQ3_XXS", .pattern = "zeros", .type = 18, .row_size = 98, .ref = 0x854a12c5d39e57c5, .deq = 0xb93a0c83ce3b6325, .chunk = 0x854a12c5d39e57c5, .chunk_bytes = 392, .chunk_imatrix = 0x854a12c5d39e57c5 },
    .{ .name = "IQ3_XXS", .pattern = "constant", .type = 18, .row_size = 98, .ref = 0x0d226f708fdf544d, .deq = 0x6c704ef155300525, .chunk = 0x0d226f708fdf544d, .chunk_bytes = 392, .chunk_imatrix = 0xb8ba28d6400f03e5 },
    .{ .name = "IQ3_XXS", .pattern = "outlier", .type = 18, .row_size = 98, .ref = 0x5968ec22e4fd0555, .deq = 0x6c248afd4c02c6cd, .chunk = 0x5968ec22e4fd0555, .chunk_bytes = 392, .chunk_imatrix = 0xe4aa40b2853097ed },
    .{ .name = "IQ3_XXS", .pattern = "alternating", .type = 18, .row_size = 98, .ref = 0xd053e216156df345, .deq = 0x35fb76449144c325, .chunk = 0xd053e216156df345, .chunk_bytes = 392, .chunk_imatrix = 0xf786fa7249238925 },
    .{ .name = "IQ3_S", .pattern = "random", .type = 21, .row_size = 110, .ref = 0x672a88653dae6b3a, .deq = 0x490d24c753ba794d, .chunk = 0x672a88653dae6b3a, .chunk_bytes = 440, .chunk_imatrix = 0x54f7e25e6962c45b },
    .{ .name = "IQ3_S", .pattern = "zeros", .type = 21, .row_size = 110, .ref = 0x08fd0a89c6878385, .deq = 0xb93a0c83ce3b6325, .chunk = 0x08fd0a89c6878385, .chunk_bytes = 440, .chunk_imatrix = 0x08fd0a89c6878385 },
    .{ .name = "IQ3_S", .pattern = "constant", .type = 21, .row_size = 110, .ref = 0x14cc8399e883afad, .deq = 0x08449e08a82f1f25, .chunk = 0x14cc8399e883afad, .chunk_bytes = 440, .chunk_imatrix = 0x5321f7ee29e3bd95 },
    .{ .name = "IQ3_S", .pattern = "outlier", .type = 21, .row_size = 110, .ref = 0x53e1b99dc74a81a5, .deq = 0x516c0bf10153ece5, .chunk = 0x53e1b99dc74a81a5, .chunk_bytes = 440, .chunk_imatrix = 0x834ed359f70dd775 },
    .{ .name = "IQ3_S", .pattern = "alternating", .type = 21, .row_size = 110, .ref = 0x74e9eb29b8330305, .deq = 0xb26b9f4ae4023125, .chunk = 0x74e9eb29b8330305, .chunk_bytes = 440, .chunk_imatrix = 0x3d4b5e151c79f1e5 },
    .{ .name = "IQ4_NL", .pattern = "random", .type = 20, .row_size = 144, .ref = 0x1d37f4b76afc08a8, .deq = 0xe0787691940f0a83, .chunk = 0x84be0bf0fd2cb65d, .chunk_bytes = 576, .chunk_imatrix = 0xcb92baffb3fbab8c },
    .{ .name = "IQ4_NL", .pattern = "zeros", .type = 20, .row_size = 144, .ref = 0xaca76e390fcfeb25, .deq = 0xbfda863198d8c325, .chunk = 0xdf4fcbd7f52e3025, .chunk_bytes = 576, .chunk_imatrix = 0xdf4fcbd7f52e3025 },
    .{ .name = "IQ4_NL", .pattern = "constant", .type = 20, .row_size = 144, .ref = 0xbd0592fbe56ad525, .deq = 0x096c72cd4c478b25, .chunk = 0x7aa58ee2535a8125, .chunk_bytes = 576, .chunk_imatrix = 0x9f1147c456257a25 },
    .{ .name = "IQ4_NL", .pattern = "outlier", .type = 20, .row_size = 144, .ref = 0x31379cda1cc8dd6d, .deq = 0x1b3030219f61f46d, .chunk = 0x4cf5505d6ace1da5, .chunk_bytes = 576, .chunk_imatrix = 0x7ddb140836ae85c5 },
    .{ .name = "IQ4_NL", .pattern = "alternating", .type = 20, .row_size = 144, .ref = 0xe5e74d36260c4865, .deq = 0xbe007cca59286f25, .chunk = 0xe5e74d36260c4865, .chunk_bytes = 576, .chunk_imatrix = 0x0b42a1ca5fbadda5 },
    .{ .name = "IQ4_XS", .pattern = "random", .type = 23, .row_size = 136, .ref = 0xa4da4904b7d796d3, .deq = 0xf297082618278752, .chunk = 0xa4da4904b7d796d3, .chunk_bytes = 544, .chunk_imatrix = 0x6dab62e4bacc4c77 },
    .{ .name = "IQ4_XS", .pattern = "zeros", .type = 23, .row_size = 136, .ref = 0xf8c92bc08650c3c5, .deq = 0xcec286564e3b6325, .chunk = 0xf8c92bc08650c3c5, .chunk_bytes = 544, .chunk_imatrix = 0xf8c92bc08650c3c5 },
    .{ .name = "IQ4_XS", .pattern = "constant", .type = 23, .row_size = 136, .ref = 0x9ec9b58429e2ff25, .deq = 0xf6b8e1c36f27c325, .chunk = 0x9ec9b58429e2ff25, .chunk_bytes = 544, .chunk_imatrix = 0xeaeb073825975c05 },
    .{ .name = "IQ4_XS", .pattern = "outlier", .type = 23, .row_size = 136, .ref = 0x0423b96b1267b0a5, .deq = 0x52206c134f396fd5, .chunk = 0x0423b96b1267b0a5, .chunk_bytes = 544, .chunk_imatrix = 0x9d3d65998a98b985 },
    .{ .name = "IQ4_XS", .pattern = "alternating", .type = 23, .row_size = 136, .ref = 0xa747fd60c30a08dd, .deq = 0xbe007cca59286f25, .chunk = 0xa747fd60c30a08dd, .chunk_bytes = 544, .chunk_imatrix = 0x933b57b8f5865c25 },
};

/// `ggml_validate_row_data` on the same fixed input.
pub const validate = struct {
    pub const q4_0_clean = true;
    pub const q4_0_nan_scale = false;
};
