//! Golden values for the ported `ggml-cpu/quants.c` dot products.
//!
//! # Provenance
//!
//! **Not a port, and not hand-written.** Generated by
//! `harness/vecdot_golden.c` run against the C reference build at
//! v0.3.0 (`c1d0e7a00`). Regenerate with `scripts/vecdot-golden`.
//!
//! # Why these exist
//!
//! Nothing on this target calls `ggml_vec_dot_*_generic`:
//! `arch-fallback.h` renames nothing from `quants.c` on ARM, and
//! `arch/arm/quants.c` supplies all 28 real entry points. So
//! `test-backend-ops` cannot reach these and neither can token
//! parity. These values, captured from the C, are the only gate
//! the generic kernels have.
//!
//! Each value is the **raw bits** of the `f32` the C writes, so the
//! comparison is exact. A dot product right to six decimals and
//! wrong in the last bit is a porting bug.
//!
//! # The five input patterns
//!
//! - `random`      the common path
//! - `zeros`       both operands all-zero: the divide-by-zero guards
//! - `signs`       fixed signs, asymmetric magnitudes, coprime
//!                 periods -- sign handling without cancellation
//! - `opposed`     y = -x, so the sum cancels to near zero while the
//!                 terms stay large
//! - `lopsided`    operands four orders of magnitude apart, x's fp16
//!                 delta subnormal -- catches a swapped scale
//!
//! Only `zeros` should produce a zero result. If another pattern
//! does, it is testing less than it looks like it is.

/// One kernel's result for each input pattern, as raw `f32` bits.
pub const Dot = struct {
    random: u32,
    zeros: u32,
    signs: u32,
    opposed: u32,
    lopsided: u32,
    ties: u32,
};

/// Elements per dot product. Divisible by every block size in play.
pub const nelem = 512;

/// One row quantizer's output for each input pattern, as an FNV-1a
/// checksum of the bytes it writes.
pub const Row = struct {
    random: u64,
    zeros: u64,
    signs: u64,
    opposed: u64,
    lopsided: u64,
    ties: u64,
};

pub const row_q8_0 = Row{
    .random = 0x5E46E3D2F27B6C33,
    .zeros = 0x9986BA9AF2021DA5,
    .signs = 0x95BF57F231C48425,
    .opposed = 0xD6251BCBF838BF03,
    .lopsided = 0xC1B16C8BB39A2109,
    .ties = 0x14303143E78B172A,
};

pub const row_q8_1 = Row{
    .random = 0x55BE9702F25F2ED2,
    .zeros = 0xB9D0059D61083025,
    .signs = 0xED16A7E36D785DA5,
    .opposed = 0x4850795A840A0EED,
    .lopsided = 0xC7D9729D6E4A36CE,
    .ties = 0x76AB02C2689358D4,
};

pub const row_q8_K = Row{
    .random = 0xC7F67C33F5D1CADB,
    .zeros = 0x9A0094294483E6C5,
    .signs = 0x9353B71451879729,
    .opposed = 0x00633ED1957EC56E,
    .lopsided = 0x36DB3C7F09A1E70E,
    .ties = 0xAA828FE99AF5BDF8,
};

pub const q1_0 = Dot{
    .random = 0x40D7F6F4, //  6.74889565
    .zeros = 0x00000000, //  0
    .signs = 0x3FA7CD00, //  1.3109436
    .opposed = 0xC30A3304, // -138.19928
    .lopsided = 0x3B30F4D3, //  0.00270013954
    .ties = 0xC51FCDA2, // -2556.85205
};

pub const q2_0 = Dot{
    .random = 0x410D04B5, //  8.81364918
    .zeros = 0x00000000, //  0
    .signs = 0x3FDFBC00, //  1.7479248
    .opposed = 0xC34ACC47, // -202.797958
    .lopsided = 0x3B67194F, //  0.00352628878
    .ties = 0x46426887, //  12442.1318
};

pub const q4_0 = Dot{
    .random = 0x41004315, //  8.01637745
    .zeros = 0x00000000, //  0
    .signs = 0x41B2A280, //  22.3293457
    .opposed = 0xC3326D24, // -178.426331
    .lopsided = 0x3B525104, //  0.00320917461
    .ties = 0x46482DAB, //  12811.417
};

pub const q4_1 = Dot{
    .random = 0x4100BDB9, //  8.04631901
    .zeros = 0x00000000, //  0
    .signs = 0x41B28DB1, //  22.3191853
    .opposed = 0xC3327A2A, // -178.477203
    .lopsided = 0x3B52E5AA, //  0.00321803475
    .ties = 0x4642CC5B, //  12467.0889
};

pub const q5_0 = Dot{
    .random = 0x4105109A, //  8.31655312
    .zeros = 0x00000000, //  0
    .signs = 0x41B2A280, //  22.3293457
    .opposed = 0xC332B9B5, // -178.725418
    .lopsided = 0x3B5A34EB, //  0.00332957017
    .ties = 0x4646220B, //  12680.5107
};

pub const q5_1 = Dot{
    .random = 0x40FE6250, //  7.94950104
    .zeros = 0x00000000, //  0
    .signs = 0x41B2D36B, //  22.3532314
    .opposed = 0xC332BE2A, // -178.742828
    .lopsided = 0x3B511B9E, //  0.00319073303
    .ties = 0x4644004D, //  12544.0752
};

pub const q8_0 = Dot{
    .random = 0x41036492, //  8.2120533
    .zeros = 0x00000000, //  0
    .signs = 0x41B153D5, //  22.1659336
    .opposed = 0xC332D182, // -178.81839
    .lopsided = 0x3B5B7E7E, //  0.00334921433
    .ties = 0x4643C4F7, //  12529.2412
};

pub const mxfp4 = Dot{
    .random = 0x40D98EEC, //  6.79869652
    .zeros = 0x00000000, //  0
    .signs = 0x41B2A280, //  22.3293457
    .opposed = 0xC3240CFB, // -164.050705
    .lopsided = 0x3B8098D6, //  0.00392446946
    .ties = 0x460F9287, //  9188.63184
};

pub const nvfp4 = Dot{
    .random = 0x40FEBFE3, //  7.96092367
    .zeros = 0x00000000, //  0
    .signs = 0x41B83794, //  23.0271378
    .opposed = 0xC33322DC, // -179.136169
    .lopsided = 0x00000000, //  0
    .ties = 0x465423AD, //  13576.9189
};

pub const q2_K = Dot{
    .random = 0x410BE650, //  8.74372864
    .zeros = 0x00000000, //  0
    .signs = 0x41B29A20, //  22.3252563
    .opposed = 0xC32D7BAA, // -173.483063
    .lopsided = 0x3B6FFC55, //  0.00366189075
    .ties = 0x46461D29, //  12679.29
};

pub const q3_K = Dot{
    .random = 0x40E12437, //  7.03567076
    .zeros = 0x00000000, //  0
    .signs = 0x41B2A54A, //  22.3307076
    .opposed = 0xC3310BC6, // -177.04599
    .lopsided = 0x3B3863E0, //  0.0028135702
    .ties = 0x464600D9, //  12672.2119
};

pub const q4_K = Dot{
    .random = 0x4105175E, //  8.31820488
    .zeros = 0x00000000, //  0
    .signs = 0x41B29A20, //  22.3252563
    .opposed = 0xC33253B2, // -178.326935
    .lopsided = 0x3B4B1AC6, //  0.00309913
    .ties = 0x4642EBF9, //  12474.9932
};

pub const q5_K = Dot{
    .random = 0x4103AC96, //  8.22963524
    .zeros = 0x00000000, //  0
    .signs = 0x41B2D195, //  22.352335
    .opposed = 0xC332D2C0, // -178.823242
    .lopsided = 0x3B530334, //  0.00321979541
    .ties = 0x4644994E, //  12582.3262
};

pub const q6_K = Dot{
    .random = 0x4103FC1D, //  8.24905109
    .zeros = 0x00000000, //  0
    .signs = 0x41B2A54A, //  22.3307076
    .opposed = 0xC33299BE, // -178.600555
    .lopsided = 0x00000000, //  0
    .ties = 0x4644B386, //  12588.8809
};

pub const tq1_0 = Dot{
    .random = 0x4122A426, //  10.1650753
    .zeros = 0x00000000, //  0
    .signs = 0x3FDFBF7F, //  1.7480315
    .opposed = 0xC34BCC4B, // -203.798019
    .lopsided = 0x3B8533E4, //  0.00406502374
    .ties = 0x465B03C3, //  14016.9404
};

pub const tq2_0 = Dot{
    .random = 0x4122A426, //  10.1650753
    .zeros = 0x00000000, //  0
    .signs = 0x3FDFBF7F, //  1.7480315
    .opposed = 0xC34BCC4B, // -203.798019
    .lopsided = 0x3B8533E4, //  0.00406502374
    .ties = 0x465B03C3, //  14016.9404
};

pub const iq2_xxs = Dot{
    .random = 0x412108DC, //  10.0646629
    .zeros = 0x00000000, //  0
    .signs = 0x41AF063C, //  21.8780441
    .opposed = 0xC32CEA50, // -172.915283
    .lopsided = 0x3B8900B2, //  0.00418099109
    .ties = 0x4633D5E0, //  11509.4688
};

pub const iq2_xs = Dot{
    .random = 0x40C250B0, //  6.07234955
    .zeros = 0x00000000, //  0
    .signs = 0x41A6DF90, //  20.8591614
    .opposed = 0xC3331474, // -179.079895
    .lopsided = 0x3B1D3D53, //  0.00239928509
    .ties = 0x464A3D6C, //  12943.3555
};

pub const iq2_s = Dot{
    .random = 0x410416A0, //  8.25552368
    .zeros = 0x00000000, //  0
    .signs = 0x419E3CD8, //  19.7797089
    .opposed = 0xC331361A, // -177.211334
    .lopsided = 0x3B55F7A4, //  0.0032648826
    .ties = 0x464244DB, //  12433.2139
};

pub const iq3_xxs = Dot{
    .random = 0x4113555E, //  9.2083416
    .zeros = 0x00000000, //  0
    .signs = 0x418036E3, //  16.0268002
    .opposed = 0xC3306716, // -176.402679
    .lopsided = 0x3B6781DD, //  0.00353252073
    .ties = 0x464DDF6A, //  13175.8535
};

pub const iq3_s = Dot{
    .random = 0x40E5C920, //  7.18080139
    .zeros = 0x00000000, //  0
    .signs = 0x41E6F8D0, //  28.8714905
    .opposed = 0xC3388940, // -184.536133
    .lopsided = 0x3B37706E, //  0.00279905973
    .ties = 0x46481CE9, //  12807.2275
};

pub const iq1_s = Dot{
    .random = 0x414BE9C1, //  12.7445688
    .zeros = 0x00000000, //  0
    .signs = 0x412D013B, //  10.8128004
    .opposed = 0xC330A3B6, // -176.639496
    .lopsided = 0x3BA651D3, //  0.00507567218
    .ties = 0x463CBC79, //  12079.1182
};

pub const iq1_m = Dot{
    .random = 0x40F9A4CE, //  7.80136776
    .zeros = 0x00000000, //  0
    .signs = 0x412B0798, //  10.6893539
    .opposed = 0xC332251F, // -178.145004
    .lopsided = 0x3B4D6964, //  0.00313433353
    .ties = 0x4634C649, //  11569.5713
};

pub const iq4_nl = Dot{
    .random = 0x4104032A, //  8.25077248
    .zeros = 0x00000000, //  0
    .signs = 0x41A1D0B9, //  20.2269154
    .opposed = 0xC3324482, // -178.267609
    .lopsided = 0x3B568AC8, //  0.00327365287
    .ties = 0x46481A50, //  12806.5781
};

pub const iq4_xs = Dot{
    .random = 0x4103565D, //  8.20858479
    .zeros = 0x00000000, //  0
    .signs = 0x41A1D340, //  20.2281494
    .opposed = 0xC3327DB2, // -178.490997
    .lopsided = 0x00000000, //  0
    .ties = 0x4648C08A, //  12848.1348
};
