//! Golden values for the ported `ggml-cpu/arch/arm/quants.c` dot products.
//!
//! # Provenance
//!
//! **Not a port, and not hand-written.** Generated by
//! `harness/vecdot_golden.c` run against the C reference build at
//! v0.3.0 (`c1d0e7a00`). Regenerate with `scripts/vecdot-golden`.
//!
//! # Why these exist
//!
//! These kernels are live: `type_traits_cpu` points at them and
//! every quantized `mul_mat` on the CPU goes through one. So
//! `test-backend-ops` and token parity do reach them -- but both
//! compare with a tolerance or at token granularity, and a
//! last-bit difference in a dot product survives either. These
//! values do not.
//!
//! Each value is the **raw bits** of the `f32` the C writes, so the
//! comparison is exact. A dot product right to six decimals and
//! wrong in the last bit is a porting bug.
//!
//! # The five input patterns
//!
//! - `random`      the common path
//! - `zeros`       both operands all-zero: the divide-by-zero guards
//! - `signs`       fixed signs, asymmetric magnitudes, coprime
//!                 periods -- sign handling without cancellation
//! - `opposed`     y = -x, so the sum cancels to near zero while the
//!                 terms stay large
//! - `lopsided`    operands four orders of magnitude apart, x's fp16
//!                 delta subnormal -- catches a swapped scale
//!
//! Only `zeros` should produce a zero result. If another pattern
//! does, it is testing less than it looks like it is.

/// One kernel's result for each input pattern, as raw `f32` bits.
pub const Dot = struct {
    random: u32,
    zeros: u32,
    signs: u32,
    opposed: u32,
    lopsided: u32,
    ties: u32,
};

/// Elements per dot product. Divisible by every block size in play.
pub const nelem = 512;

/// One row quantizer's output for each input pattern, as an FNV-1a
/// checksum of the bytes it writes.
pub const Row = struct {
    random: u64,
    zeros: u64,
    signs: u64,
    opposed: u64,
    lopsided: u64,
    ties: u64,
};

pub const row_q8_0 = Row{
    .random = 0x5E46E3D2F27B6C33,
    .zeros = 0x9986BA9AF2021DA5,
    .signs = 0x95BF57F231C48425,
    .opposed = 0xD6251BCBF838BF03,
    .lopsided = 0xC1B16C8BB39A2109,
    .ties = 0x01FFE74D11F9AE66,
};

pub const row_q8_1 = Row{
    .random = 0x55BE9702F25F2ED2,
    .zeros = 0xB9D0059D61083025,
    .signs = 0xED16A7E36D785DA5,
    .opposed = 0x4850795A840A0EED,
    .lopsided = 0xC7D9729D6E4A36CE,
    .ties = 0x5DBC8B9285B805C0,
};

pub const row_q8_K = Row{
    .random = 0xC7F67C33F5D1CADB,
    .zeros = 0x9A0094294483E6C5,
    .signs = 0x9353B71451879729,
    .opposed = 0x00633ED1957EC56E,
    .lopsided = 0x36DB3C7F09A1E70E,
    .ties = 0xAA828FE99AF5BDF8,
};

pub const q1_0 = Dot{
    .random = 0x40D7F6F3, //  6.74889517
    .zeros = 0x00000000, //  0
    .signs = 0x3FA7CD00, //  1.3109436
    .opposed = 0xC30A3304, // -138.19928
    .lopsided = 0x3B30F4D3, //  0.00270013954
    .ties = 0xC51FCDA2, // -2556.85205
};

pub const q2_0 = Dot{
    .random = 0x410D04B4, //  8.81364822
    .zeros = 0x00000000, //  0
    .signs = 0x3FDFBC00, //  1.7479248
    .opposed = 0xC34ACC48, // -202.797974
    .lopsided = 0x3B67194D, //  0.00352628832
    .ties = 0x46426886, //  12442.1309
};

pub const q4_0 = Dot{
    .random = 0x41004314, //  8.0163765
    .zeros = 0x00000000, //  0
    .signs = 0x41B2A280, //  22.3293457
    .opposed = 0xC3326D24, // -178.426331
    .lopsided = 0x3B525103, //  0.00320917438
    .ties = 0x46482DAB, //  12811.417
};

pub const q4_1 = Dot{
    .random = 0x4100BDB8, //  8.04631805
    .zeros = 0x00000000, //  0
    .signs = 0x41B28DB4, //  22.319191
    .opposed = 0xC3327A29, // -178.477188
    .lopsided = 0x3B52E5AC, //  0.00321803521
    .ties = 0x4642CC59, //  12467.0869
};

pub const q5_0 = Dot{
    .random = 0x4105109A, //  8.31655312
    .zeros = 0x00000000, //  0
    .signs = 0x41B2A280, //  22.3293457
    .opposed = 0xC332B9B6, // -178.725433
    .lopsided = 0x3B5A34EC, //  0.00332957041
    .ties = 0x4646220C, //  12680.5117
};

pub const q5_1 = Dot{
    .random = 0x40FE624F, //  7.94950056
    .zeros = 0x00000000, //  0
    .signs = 0x41B2D370, //  22.353241
    .opposed = 0xC332BE2A, // -178.742828
    .lopsided = 0x3B511B9E, //  0.00319073303
    .ties = 0x4644004D, //  12544.0752
};

pub const q8_0 = Dot{
    .random = 0x41036492, //  8.2120533
    .zeros = 0x00000000, //  0
    .signs = 0x41B153D6, //  22.1659355
    .opposed = 0xC332D183, // -178.818405
    .lopsided = 0x3B5B7E7F, //  0.00334921456
    .ties = 0x4643C4F7, //  12529.2412
};

pub const mxfp4 = Dot{
    .random = 0x40D98EEC, //  6.79869652
    .zeros = 0x00000000, //  0
    .signs = 0x41B2A280, //  22.3293457
    .opposed = 0xC3240CFC, // -164.05072
    .lopsided = 0x3B8098D6, //  0.00392446946
    .ties = 0x460F9289, //  9188.63379
};

pub const nvfp4 = Dot{
    .random = 0x40FEBFE4, //  7.96092415
    .zeros = 0x00000000, //  0
    .signs = 0x41B83794, //  23.0271378
    .opposed = 0xC33322DD, // -179.136185
    .lopsided = 0x00000000, //  0
    .ties = 0x465423B0, //  13576.9219
};

pub const q2_K = Dot{
    .random = 0x410BE650, //  8.74372864
    .zeros = 0x00000000, //  0
    .signs = 0x41B29A1F, //  22.3252544
    .opposed = 0xC32D7BAA, // -173.483063
    .lopsided = 0x3B6FFC55, //  0.00366189075
    .ties = 0x46461D2A, //  12679.291
};

pub const q3_K = Dot{
    .random = 0x40E12436, //  7.03567028
    .zeros = 0x00000000, //  0
    .signs = 0x41B2A54B, //  22.3307095
    .opposed = 0xC3310BC5, // -177.045975
    .lopsided = 0x3B3863E0, //  0.0028135702
    .ties = 0x464600D9, //  12672.2119
};

pub const q4_K = Dot{
    .random = 0x4105175E, //  8.31820488
    .zeros = 0x00000000, //  0
    .signs = 0x41B29A1F, //  22.3252544
    .opposed = 0xC33253B2, // -178.326935
    .lopsided = 0x3B4B1AC6, //  0.00309913
    .ties = 0x4642EBF7, //  12474.9912
};

pub const q5_K = Dot{
    .random = 0x4103AC95, //  8.22963428
    .zeros = 0x00000000, //  0
    .signs = 0x41B2D192, //  22.3523293
    .opposed = 0xC332D2C0, // -178.823242
    .lopsided = 0x3B530334, //  0.00321979541
    .ties = 0x4644994F, //  12582.3271
};

pub const q6_K = Dot{
    .random = 0x4103FC1D, //  8.24905109
    .zeros = 0x00000000, //  0
    .signs = 0x41B2A54B, //  22.3307095
    .opposed = 0xC33299BE, // -178.600555
    .lopsided = 0x00000000, //  0
    .ties = 0x4644B387, //  12588.8818
};

pub const tq1_0 = Dot{
    .random = 0x4122A426, //  10.1650753
    .zeros = 0x00000000, //  0
    .signs = 0x3FDFBF7F, //  1.7480315
    .opposed = 0xC34BCC4B, // -203.798019
    .lopsided = 0x3B8533E4, //  0.00406502374
    .ties = 0x465B03C3, //  14016.9404
};

pub const tq2_0 = Dot{
    .random = 0x4122A426, //  10.1650753
    .zeros = 0x00000000, //  0
    .signs = 0x3FDFBF7F, //  1.7480315
    .opposed = 0xC34BCC4B, // -203.798019
    .lopsided = 0x3B8533E4, //  0.00406502374
    .ties = 0x465B03C3, //  14016.9404
};

pub const iq2_xxs = Dot{
    .random = 0x412108DC, //  10.0646629
    .zeros = 0x00000000, //  0
    .signs = 0x41AF063C, //  21.8780441
    .opposed = 0xC32CEA50, // -172.915283
    .lopsided = 0x3B8900B1, //  0.00418099063
    .ties = 0x4633D5E0, //  11509.4688
};

pub const iq2_xs = Dot{
    .random = 0x40C250B0, //  6.07234955
    .zeros = 0x00000000, //  0
    .signs = 0x41A6DF8F, //  20.8591595
    .opposed = 0xC3331475, // -179.07991
    .lopsided = 0x3B1D3D53, //  0.00239928509
    .ties = 0x464A3D6C, //  12943.3555
};

pub const iq2_s = Dot{
    .random = 0x410416A0, //  8.25552368
    .zeros = 0x00000000, //  0
    .signs = 0x419E3CD7, //  19.779707
    .opposed = 0xC331361B, // -177.211349
    .lopsided = 0x3B55F7A4, //  0.0032648826
    .ties = 0x464244DB, //  12433.2139
};

pub const iq3_xxs = Dot{
    .random = 0x4113555E, //  9.2083416
    .zeros = 0x00000000, //  0
    .signs = 0x418036E3, //  16.0268002
    .opposed = 0xC3306716, // -176.402679
    .lopsided = 0x3B6781DD, //  0.00353252073
    .ties = 0x464DDF6A, //  13175.8535
};

pub const iq3_s = Dot{
    .random = 0x40E5C920, //  7.18080139
    .zeros = 0x00000000, //  0
    .signs = 0x41E6F8CF, //  28.8714886
    .opposed = 0xC338893F, // -184.536118
    .lopsided = 0x3B37706E, //  0.00279905973
    .ties = 0x46481CE9, //  12807.2275
};

pub const iq1_s = Dot{
    .random = 0x414BE9C1, //  12.7445688
    .zeros = 0x00000000, //  0
    .signs = 0x412D013B, //  10.8128004
    .opposed = 0xC330A3B6, // -176.639496
    .lopsided = 0x3BA651D3, //  0.00507567218
    .ties = 0x463CBC79, //  12079.1182
};

pub const iq1_m = Dot{
    .random = 0x40F9A4CE, //  7.80136776
    .zeros = 0x00000000, //  0
    .signs = 0x412B0798, //  10.6893539
    .opposed = 0xC332251F, // -178.145004
    .lopsided = 0x3B4D6965, //  0.00313433376
    .ties = 0x4634C649, //  11569.5713
};

pub const iq4_nl = Dot{
    .random = 0x4104032C, //  8.25077438
    .zeros = 0x00000000, //  0
    .signs = 0x41A1D0B8, //  20.2269135
    .opposed = 0xC3324482, // -178.267609
    .lopsided = 0x3B568AC9, //  0.0032736531
    .ties = 0x46481A50, //  12806.5781
};

pub const iq4_xs = Dot{
    .random = 0x4103565E, //  8.20858574
    .zeros = 0x00000000, //  0
    .signs = 0x41A1D340, //  20.2281494
    .opposed = 0xC3327DB0, // -178.490967
    .lopsided = 0x00000000, //  0
    .ties = 0x4648C089, //  12848.1338
};
