//! Golden values for the float dot products of `llama.cpp/ggml/src/ggml-cpu/vec.cpp`.
//!
//! **Generated by `scripts/vec-golden`. Do not edit.**
//!
//! Captured from the reference C at v0.3.0 (`c1d0e7a00`) with
//! `-ffp-contract=on`, matching the ARM quant goldens: the fusion
//! sites in `vec.cpp` are explicit `GGML_F32_VEC_FMA` intrinsics, so
//! the port can name them with `@mulAdd` and match exactly.
//!
//! Compared on **bits**, never a tolerance. These kernels are
//! accumulating reductions whose whole risk is the last bit, and no
//! other gate in this project can see them: `backend-ops` compares
//! against Metal with a tolerance, and on a Metal machine they never
//! run under `make port` at all.
//!
//! Each kernel is captured at two lengths: `nelem`, a whole number of
//! vector steps, and `nelem_tail`, which leaves a scalar remainder.
//! The tails accumulate in a different type from the bodies, so a
//! port that gets the body right and the tail wrong passes the first
//! and fails the second.

/// One kernel's result for each input pattern, as raw `f32` bits.
pub const Dot = struct {
    random: u32,
    zeros: u32,
    signs: u32,
    opposed: u32,
    lopsided: u32,
    ties: u32,
    skewed: u32,
};

/// Elements per dot product: a whole number of vector steps.
pub const nelem = 512;

/// A length that leaves a scalar tail for both the f32 and f16 steps.
pub const nelem_tail = 519;

pub const dot_f32 = Dot{
    .random = 0x41037124, //  8.21512222
    .zeros = 0x00000000, //  0
    .signs = 0x41B40000, //  22.5
    .opposed = 0xC332C4B9, // -178.768448
    .lopsided = 0x3B575ABF, //  0.00328604854
    .ties = 0x46451500, //  12613.25
    .skewed = 0xC035D443, // -2.84108043
};

pub const dot_f16 = Dot{
    .random = 0x41037C00, //  8.21777344
    .zeros = 0x00000000, //  0
    .signs = 0x41B40000, //  22.5
    .opposed = 0xC332CC00, // -178.796875
    .lopsided = 0x3B576C00, //  0.00328707695
    .ties = 0x4644E000, //  12600
    .skewed = 0xC035F950, // -2.84334183
};

pub const dot_bf16 = Dot{
    .random = 0x410352AF, //  8.20768642
    .zeros = 0x00000000, //  0
    .signs = 0x41B40000, //  22.5
    .opposed = 0xC332C344, // -178.762756
    .lopsided = 0x3B579F9E, //  0.00329015357
    .ties = 0x46451500, //  12613.25
    .skewed = 0xC035C686, // -2.84024191
};

pub const dot_f32_tail = Dot{
    .random = 0x410CFA3F, //  8.81109524
    .zeros = 0x00000000, //  0
    .signs = 0x41B30000, //  22.375
    .opposed = 0xC336C411, // -182.765884
    .lopsided = 0x3B66FA40, //  0.00352443755
    .ties = 0x46446600, //  12569.5
    .skewed = 0xC0363C6B, // -2.84743762
};

pub const dot_f16_tail = Dot{
    .random = 0x410D048A, //  8.81360817
    .zeros = 0x00000000, //  0
    .signs = 0x41B30000, //  22.375
    .opposed = 0xC336CB67, // -182.79454
    .lopsided = 0x3B670AF0, //  0.0035254322
    .ties = 0x46443100, //  12556.25
    .skewed = 0xC0366186, // -2.84970236
};

pub const dot_bf16_tail = Dot{
    .random = 0x410CD3F6, //  8.80174828
    .zeros = 0x00000000, //  0
    .signs = 0x41B30000, //  22.375
    .opposed = 0xC336C1F8, // -182.75769
    .lopsided = 0x3B671EAF, //  0.00352660916
    .ties = 0x46446600, //  12569.5
    .skewed = 0xC0362E63, // -2.84658122
};
